const gameData = [
  // --- 1. 記憶力 ---
  { no: 1, name: "絵合わせ", file: "2.html", icon: "🍎", desc: "トランプの神経衰弱。ペアを見つける。", active: true },
  { no: 2, name: "光の順番", file: "6.html", icon: "💡", desc: "光ったボタンの順番を覚えて再現する。", active: true },
  { no: 3, name: "瞬間記憶（数字）", file: "", icon: "🔢", desc: "画面に3秒だけ出た数字を答える。", active: false },
  { no: 4, name: "瞬間記憶（絵）", file: "", icon: "🖼️", desc: "画面に出たイラストの位置を覚える。", active: false },
  { no: 5, name: "お買い物メモ", file: "", icon: "🛒", desc: "リストを覚えて後で選ぶ。", active: false },
  { no: 6, name: "後出しジャンケン", file: "", icon: "✊", desc: "前の手を覚えて勝つ手を出す。", active: false },
  { no: 7, name: "音感メモリー", file: "", icon: "🎵", desc: "音階を覚えて再現する。", active: false },
  { no: 8, name: "イラスト足し算", file: "", icon: "➕", desc: "前の絵を答える（Nバック課題）。", active: false },
  { no: 9, name: "人の顔覚え", file: "", icon: "👨", desc: "顔と名前を覚えるクイズ。", active: false },
  { no: 10, name: "順番覚え", file: "", icon: "🍽️", desc: "注文の順番を覚える。", active: false },
  { no: 11, name: "色覚え", file: "", icon: "🎨", desc: "画面の色を覚える。", active: false },
  { no: 12, name: "配置覚え", file: "", icon: "碁", desc: "黒石の場所を覚える。", active: false },
  { no: 13, name: "隠れたのは誰？", file: "", icon: "🙈", desc: "消えた動物を当てる。", active: false },
  { no: 14, name: "電話番号記憶", file: "", icon: "📞", desc: "番号を覚えて入力する。", active: false },
  { no: 15, name: "フラッシュ暗算", file: "", icon: "⚡️", desc: "次々に出る数字を足す。", active: false },

  // --- 2. 反射神経 ---
  { no: 16, name: "もぐら叩き", file: "1.html", icon: "🐹", desc: "出てくるマトを素早くタップ。", active: true },
  { no: 17, name: "数字タッチ", file: "3.html", icon: "🔢", desc: "1から順に素早く押す。", active: true },
  { no: 18, name: "ストップウォッチ", file: "", icon: "⏱️", desc: "10.00秒ジャストで止める。", active: false },
  { no: 19, name: "連打ゲーム", file: "", icon: "🔥", desc: "10秒間で何回押せるか。", active: false },
  { no: 20, name: "信号機ゲーム", file: "", icon: "🚦", desc: "青なら進む、赤なら止まる。", active: false },
  { no: 21, name: "蚊たたき", file: "", icon: "🦟", desc: "飛び回る蚊を退治。", active: false },
  { no: 22, name: "落ちものキャッチ", file: "", icon: "🧺", desc: "フルーツをカゴで受ける。", active: false },
  { no: 23, name: "居合切り", file: "", icon: "⚔️", desc: "「！」の瞬間に押す。", active: false },
  { no: 24, name: "リズムタップ", file: "", icon: "🥁", desc: "リズムに合わせて押す。", active: false },
  { no: 25, name: "スロット目押し", file: "", icon: "🎰", desc: "絵柄を揃える。", active: false },
  { no: 26, name: "魚釣り", file: "", icon: "🎣", desc: "重なった瞬間にタップ。", active: false },
  { no: 27, name: "だるま落とし", file: "", icon: "🔨", desc: "素早く弾く。", active: false },
  { no: 28, name: "シェイク！", file: "", icon: "📱", desc: "スマホを振る回数を競う。", active: false },
  { no: 29, name: "数字早探し", file: "", icon: "👀", desc: "最大値を素早く探す。", active: false },
  { no: 30, name: "忍者探し", file: "", icon: "🥷", desc: "隠れた忍者をタップ。", active: false },

  // --- 3. 言語・知識 ---
  { no: 31, name: "難読漢字（植物）", file: "", icon: "🌹", desc: "「薔薇」などの読み方。", active: false },
  { no: 32, name: "難読漢字（魚）", file: "", icon: "🐟", desc: "「鯱」などの読み方。", active: false },
  { no: 33, name: "難読漢字（地名）", file: "", icon: "🗺️", desc: "地名の読み方クイズ。", active: false },
  { no: 34, name: "ことわざ完成", file: "", icon: "🐕", desc: "ことわざの下の句を当てる。", active: false },
  { no: 35, name: "四字熟語", file: "", icon: "四", desc: "空欄に入る漢字を選ぶ。", active: false },
  { no: 36, name: "反対語クイズ", file: "", icon: "↔️", desc: "反対の意味の言葉を選ぶ。", active: false },
  { no: 37, name: "類義語クイズ", file: "", icon: "≒", desc: "同じ意味の言葉を選ぶ。", active: false },
  { no: 38, name: "英語クイズ", file: "", icon: "🔤", desc: "英単語の意味を当てる。", active: false },
  { no: 39, name: "県庁所在地", file: "", icon: "🏯", desc: "県庁所在地を当てる。", active: false },
  { no: 40, name: "昭和クイズ", file: "", icon: "📺", desc: "昭和の出来事クイズ。", active: false },
  { no: 41, name: "部首当て", file: "", icon: "氵", desc: "漢字の部首を当てる。", active: false },
  { no: 42, name: "季節の言葉", file: "", icon: "🌸", desc: "季語や行事のクイズ。", active: false },
  { no: 43, name: "国旗当て", file: "", icon: "🎌", desc: "どこの国の国旗？", active: false },
  { no: 44, name: "野菜の花当て", file: "", icon: "🥒", desc: "花の写真から野菜を当てる。", active: false },
  { no: 45, name: "バラバラ漢字", file: "", icon: "🧩", desc: "合体してできる漢字は？", active: false },
  { no: 46, name: "アナグラム", file: "", icon: "🔄", desc: "文字を並べ替えて言葉にする。", active: false },
  { no: 47, name: "クロスワード", file: "", icon: "✏️", desc: "単語パズル。", active: false },
  { no: 48, name: "しりとり対決", file: "", icon: "🔚", desc: "CPUとしりとり。", active: false },
  { no: 49, name: "穴埋め川柳", file: "", icon: "🏮", desc: "五七五を埋める。", active: false },
  { no: 50, name: "朗読速度測定", file: "", icon: "📖", desc: "読む時間を測る。", active: false },

  // --- 4. 計算・論理 ---
  { no: 51, name: "計算ドリル", file: "4.html", icon: "🧮", desc: "足し算・引き算の早解き。", active: true },
  { no: 52, name: "お釣り計算", file: "", icon: "💴", desc: "買い物のお釣りを計算。", active: false },
  { no: 53, name: "割り勘計算", file: "", icon: "🍻", desc: "一人いくらか計算。", active: false },
  { no: 54, name: "穴埋め計算", file: "", icon: "❓", desc: "式の空欄を埋める。", active: false },
  { no: 55, name: "大小比較", file: "", icon: "⚖️", desc: "どっちの数字が大きい？", active: false },
  { no: 56, name: "単位変換", file: "", icon: "📏", desc: "kmをmに直すなど。", active: false },
  { no: 57, name: "天秤パズル", file: "", icon: "⚖️", desc: "重さを釣り合わせる。", active: false },
  { no: 58, name: "時計の読み方", file: "", icon: "🕒", desc: "時間を計算する。", active: false },
  { no: 59, name: "規則性クイズ", file: "", icon: "📈", desc: "次に来る数字は？", active: false },
  { no: 60, name: "メイク10", file: "", icon: "🔟", desc: "4つの数字で10を作る。", active: false },
  { no: 61, name: "魔法陣", file: "", icon: "🧙", desc: "縦横斜めの合計を揃える。", active: false },
  { no: 62, name: "数独（簡易）", file: "", icon: "9️⃣", desc: "4×4の簡単ナンプレ。", active: false },
  { no: 63, name: "筆算パズル", file: "", icon: "📝", desc: "虫食い算。", active: false },
  { no: 64, name: "コイン数え", file: "", icon: "💰", desc: "小銭の合計金額。", active: false },
  { no: 65, name: "買い物カゴ", file: "", icon: "🧺", desc: "カゴの中身の合計。", active: false },

  // --- 5. 観察力 ---
  { no: 66, name: "仲間はずれ", file: "7.html", icon: "👀", desc: "違う絵文字を探す。", active: true },
  { no: 67, name: "文字探し", file: "", icon: "🔍", desc: "特定の文字を探す。", active: false },
  { no: 68, name: "アハ体験", file: "", icon: "🖼️", desc: "どこが変わった？", active: false },
  { no: 69, name: "間違い探し", file: "", icon: "🤔", desc: "左右の絵の違いを探す。", active: false },
  { no: 70, name: "動体視力", file: "", icon: "🚄", desc: "横切ったものは何？", active: false },
  { no: 71, name: "重なり図形", file: "", icon: "🔺", desc: "一番下の図形は？", active: false },
  { no: 72, name: "迷路", file: "", icon: "🗺️", desc: "ゴールまでなぞる。", active: false },
  { no: 73, name: "同じ絵探し", file: "", icon: "👯", desc: "ペアを探す。", active: false },
  { no: 74, name: "シェルゲーム", file: "", icon: "🥤", desc: "ボールが入ったカップを追う。", active: false },
  { no: 75, name: "ウォーリー系", file: "", icon: "🕵️", desc: "人混みから探す。", active: false },
  { no: 76, name: "色の濃淡", file: "", icon: "🎨", desc: "違う色を探す。", active: false },
  { no: 77, name: "シルエット", file: "", icon: "👤", desc: "影の形を当てる。", active: false },
  { no: 78, name: "拡大クイズ", file: "", icon: "🔎", desc: "拡大写真から当てる。", active: false },
  { no: 79, name: "モザイク", file: "", icon: "🌫️", desc: "モザイクの正体は？", active: false },
  { no: 80, name: "点つなぎ", file: "", icon: "✏️", desc: "点を順に結ぶ。", active: false },

  // --- 6. 判断力・空間 ---
  { no: 81, name: "色並べ", file: "5.html", icon: "🌈", desc: "色をグラデーションにする。", active: true },
  { no: 82, name: "後出し（負け）", file: "", icon: "✌️", desc: "指示通りに負ける。", active: false },
  { no: 83, name: "ストループ", file: "", icon: "🎨", desc: "文字の色を答える。", active: false },
  { no: 84, name: "仕分けゲーム", file: "", icon: "🗑️", desc: "ゴミを分別する。", active: false },
  { no: 85, name: "展開図", file: "", icon: "🎲", desc: "組み立てた形を当てる。", active: false },
  { no: 86, name: "ブロック数え", file: "", icon: "🧱", desc: "積み木の数を数える。", active: false },
  { no: 87, name: "鏡文字", file: "", icon: "🪞", desc: "鏡に映った文字を読む。", active: false },
  { no: 88, name: "地図記号", file: "", icon: "📍", desc: "記号の意味を答える。", active: false },
  { no: 89, name: "方角クイズ", file: "", icon: "🧭", desc: "北を向いて右は？", active: false },
  { no: 90, name: "回転パズル", file: "", icon: "🔄", desc: "正しい向きにする。", active: false },
  { no: 91, name: "一筆書き", file: "", icon: "✏️", desc: "一筆書きできる？", active: false },
  { no: 92, name: "タングラム", file: "", icon: "🔺", desc: "形を組み合わせて作る。", active: false },
  { no: 93, name: "あみだくじ", file: "", icon: "🪜", desc: "当たりをたどる。", active: false },
  { no: 94, name: "信号渡し", file: "", icon: "🚦", desc: "渡れるタイミングを選ぶ。", active: false },
  { no: 95, name: "左右盲", file: "", icon: "🚩", desc: "旗揚げゲーム。", active: false },

  // --- 7. その他 ---
  { no: 96, name: "おみくじ", file: "", icon: "⛩️", desc: "今日の運勢。", active: false },
  { no: 97, name: "ルーレット", file: "", icon: "🎰", desc: "ラッキーアイテム。", active: false },
  { no: 98, name: "10秒瞑想", file: "", icon: "🧘", desc: "リラックスタイム。", active: false },
  { no: 99, name: "深呼吸ガイド", file: "", icon: "🌬️", desc: "呼吸を整える。", active: false },
  { no: 100, name: "百マス計算", file: "", icon: "💯", desc: "ラスボス。計算アタック。", active: false }
];